name: Temp

on: push

jobs:
  temp:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v3
      - run: bun install
      - run: make install

      - uses: actions/checkout@v3
        with:
          repository: codecrafters-io/build-your-own-sqlite
          path: course

      - run: cd course && course-sdk temp
